import { defineStore } from "pinia";
// import axios from 'axios';
import fetchClient from "@/utils/fetchClient";

export const useDishTypeStore =  defineStore('dishTypeStore', {
    state:() => ({
        dishTypes: [],
    }),
    getters:{
        getDishTypes: (state) => {
            return state.dishTypes;
        }
    },
    actions: {
        async fetchDishTypes () {
            // fetch dishtypes from contentful, CDA
            try {
                const response = await fetchClient.get('/api/dishtypes');
                if(response.data) {
                    this.$state.dishTypes = response.data;
                } else {
                    alert('No dishtypes currently');
                }
            } catch (error) {
                console.error('Error fetching dish types:', error);
            }
        },
        async createDishType(newDishType) {
            console.log('DishType data is ', newDishType);
            try {
                const response = await fetchClient.post('/api/createDishType', {dishTypeData:newDishType});
                if(response.data) {
                    console.log('the new dishtype is', response.data);
                }
            } catch (error) {
                console.error('Error creating dish type:', error);
            }
        },
        async deleteDishType(id) {
            // think about using the id being generated by contentful 
            console.log(id);
        },
        async editDishType(id) {
            // edit dishType name or alias
            console.log(id);
        }
    }
})